-- Generated by nwg-displays on 2026-07-12 at 12:49:22. Do not edit manually.

hl.monitor({
    output = "desc:Samsung Display Corp. ATNA33AA08-0",
    mode = "2880x1800@60.0",
    position = "9406x1440",
    scale = 1.8
})
hl.monitor({
    output = "desc:LG Electronics 27GL850 912NTCZ32251",
    mode = "2560x1440@74.97",
    position = "3296x476",
    scale = 1.0
})
hl.monitor({
    output = "desc:LG Electronics LG ULTRAGEAR+ 409NTRL7L614",
    mode = "3840x2160@144.05",
    position = "5856x330",
    scale = 1.25
})
hl.monitor({
    output = "desc:Samsung Electric Company LC27G7xT H4ZT400132",
    mode = "2560x1440@59.95",
    position = "8928x0",
    scale = 1.0
})
